name: blabla
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  cupertino_icons: ^1.0.2
  device_preview:
  dio: ^4.0.1

  flutter:
    sdk: flutter

  flutter_bloc: ^7.3.3
  flutter_native_splash: ^1.3.1
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^0.23.0+1
  flutter_tts: ^3.2.2
  flutter_zoom_drawer: ^2.1.1
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0
  get_it:
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+4
  injectable: ^1.5.0
  intl: ^0.17.0
  path_provider: ^2.0.6
  slide_drawer: ^1.0.3
  url_launcher: ^6.0.12
  

dev_dependencies:
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  injectable_generator:  
  lint: ^1.7.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"



flutter:

  assets:
    - assets/
    - assets/onboarding/
    - assets/bots/
    
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/gilroy-medium.ttf
    
  uses-material-design: true
